# ▄▀█ █░█ ▀█▀ █▀█ █▀ ▀█▀ ▄▀█ █▀█ ▀█▀
# █▀█ █▄█ ░█░ █▄█ ▄█ ░█░ █▀█ █▀▄ ░█░
# ============================================================

# --- ENVIRONMENT VARIABLES ---
env = WAYLAND_DISPLAY, wayland-1
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland
env = XDG_SESSION_DESKTOP, Hyprland
env = QT_QPA_PLATFORM, wayland;xcb
env = QT_WAYLAND_DISABLE_WINDOWDECORATION, 1
env = GDK_BACKEND, wayland,x11
env = SDL_VIDEODRIVER, wayland
env = CLUTTER_BACKEND, wayland
env = MOZ_ENABLE_WAYLAND, 1

# --- NOTIFICATION DAEMON ---
exec-once = pkill dunst; dunst

# --- WALLPAPER DAEMON ---
exec-once = swww-daemon

# --- RESTORE THEME ---
exec-once = ~/.config/hypr/scripts/toggle-theme.sh restore

# --- POLKIT (Authentication Agent) ---
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# --- IDLE MANAGEMENT ---
exec-once = hypridle

# --- CLIPBOARD MANAGER ---
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# --- XDG PORTAL ---
exec-once = sleep 1 && /usr/lib/xdg-desktop-portal-hyprland &
exec-once = sleep 2 && /usr/lib/xdg-desktop-portal &
