-- ============================================================
--  HYPRLAND LUA CONFIGURATION (Hyprland v0.55+)
-- ============================================================

hl.config({ autogenerated = false }) -- Disable the autogenerated config warning

-- ------------------------------------------------------------
--  VARIABLES
-- ------------------------------------------------------------
local mainMod  = "SUPER"
local left     = "h"
local down     = "j"
local up       = "k"
local right    = "l"

local term     = "alacritty"
local menu     = "rofi -show drun"
local browser1 = "zen-browser"
local browser2 = "brave"
local files    = "dolphin"

-- ------------------------------------------------------------
--  MONITORS & WORKSPACES
-- ------------------------------------------------------------
-- Laptop display (eDP-1)
hl.monitor({ output = "eDP-1", mode = "1920x1080", position = "0x0", scale = "1" })
-- External display (HDMI-A-1) to the right
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080", position = "1920x0", scale = "1" })
-- Fallback
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = "1" })

-- Assign Workspaces to Monitors
for i = 1, 5 do
    hl.workspace_rule({ workspace = tostring(i), monitor = "eDP-1" })
end
for i = 6, 10 do
    hl.workspace_rule({ workspace = tostring(i), monitor = "HDMI-A-1" })
end

-- ------------------------------------------------------------
--  INPUT
-- ------------------------------------------------------------
hl.config({
    input = {
        kb_layout = "eu",
        kb_variant = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 to 1.0 (0 = no modification)
        accel_profile = "adaptive",
        touchpad = {
            natural_scroll = true,
            tap_to_click = true,
            disable_while_typing = true,
            middle_button_emulation = true,
            scroll_factor = 1.0,
        },
    },
    cursor = {
        no_hardware_cursors = false,
    },
})

-- Gestures (New v0.51+ syntax)
hl.gesture({ fingers = 3, direction = "horizontal", action = "workspace" })

-- ------------------------------------------------------------
--  VISUALS & THEME (Solid Sway-like borders & Uniform Gaps)
-- ------------------------------------------------------------
hl.config({
    general = {
        gaps_in = 6,
        gaps_out = 6, -- Uniform outer gaps
        border_size = 1,
        col = {
            active_border = "rgba(ffffffff)",   -- Celestial white active border
            inactive_border = "rgba(333333ff)", -- Sway grey inactive border
        },
        layout = "dwindle",
    },
    decoration = {
        rounding = 8,
        blur = {
            enabled = true,
            size = 8,
            passes = 2,
            new_optimizations = true,
            xray = false,
            noise = 0.02,
            contrast = 0.9,
            brightness = 0.8,
        },
        shadow = {
            enabled = true,
            range = 12,
            render_power = 3,
            color = 0xcc1a1a2e,
            color_inactive = 0x661a1a2e,
        },
        active_opacity = 1.0,
        inactive_opacity = 0.95,
        fullscreen_opacity = 1.0,
    },
    animations = {
        enabled = false,
    },
})

-- Animations Bezier Curves
hl.curve("smoothOut", { type = "bezier", points = { {0.36, 0}, {0.66, -0.56} } })
hl.curve("smoothIn",  { type = "bezier", points = { {0.25, 1}, {0.5, 1} } })
hl.curve("overshot",  { type = "bezier", points = { {0.05, 0.9}, {0.1, 1.05} } })
hl.curve("linear",    { type = "bezier", points = { {0.0, 0.0}, {1.0, 1.0} } })

-- Animations Config
hl.animation({ leaf = "windows",     enabled = false, speed = 5,  bezier = "overshot",  style = "slide" })
hl.animation({ leaf = "windowsOut",  enabled = false, speed = 4,  bezier = "smoothOut", style = "slide" })
hl.animation({ leaf = "windowsMove", enabled = false, speed = 4,  bezier = "smoothIn" })
hl.animation({ leaf = "fade",        enabled = false, speed = 5,  bezier = "smoothIn" })
hl.animation({ leaf = "fadeOut",     enabled = false, speed = 4,  bezier = "smoothOut" })
hl.animation({ leaf = "border",      enabled = false, speed = 10, bezier = "linear" })
hl.animation({ leaf = "workspaces",  enabled = false, speed = 5,  bezier = "overshot",  style = "slidevert" })

-- ------------------------------------------------------------
--  LAYOUTS & MISC
-- ------------------------------------------------------------
hl.config({
    dwindle = {
        preserve_split = true,
        smart_resizing = true,
    },
    master = {
        new_status = "master",
        mfact = 0.55,
    },
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        background_color = 0x000000,
        animate_manual_resizes = true,
        enable_swallow = true,
        swallow_regex = "^(alacritty)$",
        key_press_enables_dpms = true,
        mouse_move_enables_dpms = false,
    },
})

-- ------------------------------------------------------------
--  AUTOSTART & ENVIRONMENT
-- ------------------------------------------------------------
hl.env("WAYLAND_DISPLAY", "wayland-1")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
hl.env("QT_QPA_PLATFORM", "wayland;xcb")
hl.env("QT_WAYLAND_DISABLE_WINDOWDECORATION", "1")
hl.env("GDK_BACKEND", "wayland,x11")
hl.env("SDL_VIDEODRIVER", "wayland")
hl.env("CLUTTER_BACKEND", "wayland")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("XCURSOR_THEME", "Vimix-cursors")
hl.env("XCURSOR_SIZE", "30")

hl.on("hyprland.start", function ()
    hl.exec_cmd("pkill dunst; dunst")
    hl.exec_cmd("swww-daemon")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("wl-paste --type text --watch cliphist store")
    hl.exec_cmd("wl-paste --type image --watch cliphist store")
    hl.exec_cmd("sleep 1 && /usr/lib/xdg-desktop-portal-hyprland &")
    hl.exec_cmd("sleep 2 && /usr/lib/xdg-desktop-portal &")
    hl.exec_cmd("~/.config/hypr/scripts/toggle-theme.sh restore")
end)

-- ------------------------------------------------------------
--  WINDOW RULES
-- ------------------------------------------------------------
-- Floating rules
hl.window_rule({ match = { title = "^(.*)(\\bconfirm\\b|\\bdialog\\b|\\bprompt\\b|\\balert\\b)(.*)$" }, float = true })
hl.window_rule({ match = { xdg_tag = "^(dialog|modal)$" }, float = true })
hl.window_rule({ match = { initial_class = "^(file_progress)$" }, float = true })
hl.window_rule({ match = { class = "^(org.freedesktop.impl.portal.desktop.kde)$" }, float = true })

-- Zoom Annotations & Pencil Fix
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.window_rule({ match = { title = "^(Zoom)(.*)$" }, float = true })
hl.window_rule({ match = { title = "^(zoom)$", class = "^(zoom)$" }, no_focus = true, no_blur = true, no_shadow = true })
hl.window_rule({ match = { title = "^(Zoom Meeting)(.*)$" }, tile = true })

-- Cisco Packet Tracer
hl.window_rule({ match = { class = "^(PacketTracer)$" }, float = true, rounding = 8 })
hl.window_rule({ match = { class = "^(PacketTracer)$", title = "^(Cisco Packet Tracer)$" }, tile = true })

-- Desktop Portals & Dialogs
hl.window_rule({ match = { class = "^(xdg-desktop-portal-gtk)$" }, float = true })
hl.window_rule({ match = { title = "^(Open File)(.*)$" }, float = true })
hl.window_rule({ match = { title = "^(Select a File)(.*)$" }, float = true })
hl.window_rule({ match = { title = "^(Choose wallpaper)(.*)$" }, float = true })
hl.window_rule({ match = { title = "^(Save File)(.*)$" }, float = true })

-- Popups
hl.window_rule({ match = { class = "^(pavucontrol)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, float = true })
hl.window_rule({ match = { class = "^(polkit-kde-authentication-agent-1)$" }, float = true })

-- Opacities
hl.window_rule({ match = { class = "^(alacritty)$" }, opacity = "0.75 0.70" })
hl.window_rule({ match = { class = "^(dolphin)$" }, opacity = "0.95 0.90" })

-- ------------------------------------------------------------
--  KEYBINDINGS
-- ------------------------------------------------------------
-- Mouse bindings
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Applications
hl.bind(mainMod .. " + Return", hl.dsp.exec_cmd(term))
hl.bind(mainMod .. " + Q", hl.dsp.window.close())
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd("~/.config/hypr/scripts/rofi-launcher.sh"))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd(files))
hl.bind(mainMod .. " + Z", hl.dsp.exec_cmd(browser1))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser2))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("antigravity-ide"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(term .. " -e nvim"))
hl.bind(mainMod .. " + V", hl.dsp.exec_cmd("protonvpn-app"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("~/.config/hypr/scripts/display-monitor.sh"))

-- System Controls
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("hyprctl reload"))
hl.bind(mainMod .. " + SHIFT + E", hl.dsp.exec_cmd("~/.config/rofi/powermenu_active.sh"))
hl.bind(mainMod .. " + BackSpace", hl.dsp.exec_cmd("~/.config/rofi/powermenu_active.sh"))
-- hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-wallpaper.sh"))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-theme.sh"))
hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("~/.config/hypr/scripts/keybinds-help.sh"))

-- Rofi Addons
hl.bind(mainMod .. " + ALT + right", hl.dsp.exec_cmd("~/.config/hypr/scripts/rofi-cycler.sh launcher style"))
hl.bind(mainMod .. " + ALT + down",  hl.dsp.exec_cmd("~/.config/hypr/scripts/rofi-cycler.sh launcher type"))
hl.bind(mainMod .. " + ALT + left",  hl.dsp.exec_cmd("~/.config/hypr/scripts/rofi-cycler.sh powermenu style"))
hl.bind(mainMod .. " + ALT + up",    hl.dsp.exec_cmd("~/.config/hypr/scripts/rofi-cycler.sh powermenu type"))
hl.bind(mainMod .. " + SHIFT + S",   hl.dsp.exec_cmd("~/.config/rofi/applets/bin/screenshot.sh"))
hl.bind(mainMod .. " + A",           hl.dsp.exec_cmd("~/.config/rofi/applets/bin/apps.sh"))
hl.bind(mainMod .. " + M",           hl.dsp.exec_cmd("~/.config/rofi/applets/bin/mpd.sh"))

-- Hardware & Media
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh vol_mute"),        { repeat_rate = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh vol_down"),        { repeat_rate = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh vol_up"),          { repeat_rate = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh bright_down"),     { repeat_rate = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh bright_up"),       { repeat_rate = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("pactl set-source-mute @DEFAULT_SOURCE@ toggle"))

-- Fallback (Laptop function keys)
hl.bind("F1", hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh vol_mute"))
hl.bind("F2", hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh vol_down"))
hl.bind("F3", hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh vol_up"))
hl.bind("F5", hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh bright_down"))
hl.bind("F6", hl.dsp.exec_cmd("~/.config/hypr/scripts/osd.sh bright_up"))

-- Screenshots
hl.bind("Print",         hl.dsp.exec_cmd("sh -c 'mkdir -p ~/Pictures/Screenshots && FILE=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim -g \"$(slurp)\" - | swappy -f - -o \"$FILE\" && [ -f \"$FILE\" ] && wl-copy < \"$FILE\"'"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("sh -c 'mkdir -p ~/Pictures/Screenshots && FILE=~/Pictures/Screenshots/$(date +%Y-%m-%d_%H-%M-%S).png && grim - | swappy -f - -o \"$FILE\" && [ -f \"$FILE\" ] && wl-copy < \"$FILE\"'"))

-- Window Navigation (Vim-style)
hl.bind(mainMod .. " + " .. left,  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + " .. down,  hl.dsp.focus({ direction = "down" }))
hl.bind(mainMod .. " + " .. up,    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + " .. right, hl.dsp.focus({ direction = "right" }))

-- Window Navigation (Arrow keys)
hl.bind(mainMod .. " + left",  hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up",    hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down",  hl.dsp.focus({ direction = "down" }))

-- Split / Layout Control
hl.bind(mainMod .. " + ALT + V", hl.dsp.layout("togglesplit"))

-- Floating & Fullscreen
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SHIFT + F",     hl.dsp.window.fullscreen({ action = "toggle" }))

-- Scratchpad
hl.bind(mainMod .. " + minus",       hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + minus", hl.dsp.window.move({ workspace = "special:magic" }))

-- Workspaces
for i = 1, 10 do
    local key = i % 10
    hl.bind(mainMod .. " + " .. key,         hl.dsp.focus({ workspace = i }))
    hl.bind(mainMod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i }))
end
